# Site setting
# 
# to test on local system, type:
#   > bundle exec jekyll serve
# and open web-browser at:
#   http://127.0.0.1:4000
# 

## infos
title: SPECFEM3D_GLOBE 
description: > # this means to ignore newlines until "baseurl:"
  SPECFEM3D_GLOBE simulates global and regional (continental-scale) seismic wave propagation.

## more infos
#email: your-email@domain.com
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

## Build settings
#markdown: kramdown

## Themes
#theme: minima
#theme: jekyll-theme-minimal
theme: jekyll-theme-cayman

## Gems
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

